# pre-commit 1.1.0 is required for `exclude`
# however `minimum_pre_commit_version` itself requires 1.15.0
minimum_pre_commit_version: "1.15.0"

exclude: "^(\
yt/extern\
|yt/frontends/stream/sample_data\
|yt/units\
|scripts\
|benchmark\
|setupext.py\
|yt/visualization/_colormap_data.py\
)"

ci:
    autofix_prs: false
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: check-yaml

# TODO: replace this with ruff when it supports embedded python blocks
# see https://github.com/astral-sh/ruff/issues/8237
-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==24.3.0]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.2
  hooks:
  - id: ruff-format
  - id: ruff
    args: [
      --fix,
      --show-fixes,
    ]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks

- repo: https://github.com/MarcoGorelli/cython-lint
  rev: v0.16.2
  hooks:
  - id: cython-lint
    args: [--no-pycodestyle]
