# pre-commit 1.1.0 is required for `exclude`
# however `minimum_pre_commit_version` itself requires 1.15.0
minimum_pre_commit_version: "1.15.0"

exclude: "^(\
yt/extern\
|yt/frontends/stream/sample_data\
|yt/units\
|scripts\
|benchmark\
|setupext.py\
|yt/visualization/_colormap_data.py\
)"

ci:
    autofix_prs: false
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: check-yaml

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black-jupyter

-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.1.0]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.241
  hooks:
  - id: ruff
    args: [--fix]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.6.1
  hooks:
  - id: nbqa-ruff
    args: [--fix, --extend-ignore=E402]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks

- repo: https://github.com/MarcoGorelli/cython-lint
  rev: v0.12.4
  hooks:
  - id: cython-lint
    args: [--no-pycodestyle]
