# pre-commit 1.1.0 is required for `exclude`
# however `minimum_pre_commit_version` itself requires 1.15.0
minimum_pre_commit_version: "1.15.0"

# note: isort can't be applied to yt/__init__.py because it creates circular imports
exclude: "^(\
yt/extern\
|yt/frontends/stream/sample_data\
|yt/units\
|scripts\
|benchmark\
|setupext.py\
|yt/visualization/_colormap_data.py\
|yt/__init__.py\
)"

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
# Note that in rare cases, flynt may undo some of the formating from black.
# A stable configuration is run black last.
-   repo: https://github.com/ikamensh/flynt
    rev: '0.52'
    hooks:
    - id: flynt

-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/timothycrosley/isort
    rev: '5.6.4'
    hooks:
    - id: isort
      additional_dependencies: [toml]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.1'
    hooks:
    - id: flake8
      additional_dependencies: [mccabe, flake8-bugbear]
