name: type checking

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - yt/**/*.py
      - setup.cfg
      - .github/workflows/type-checking.yaml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: type check
    timeout-minutes: 60

    concurrency:
      # auto-cancel any in-progress job *on the same branch*
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # run with oldest supported python version
        # so that we always get compatible versions of
        # core dependencies at type-check time
        python-version: '3.9'

    - name: Build
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -e .[typecheck]

    - run: python -m pip list

    - name: Run mypy
      run: mypy yt
